apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sealed-secret-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johnasbaghi/argocd-sealed-secret-demo.git
    targetRevision: HEAD
    path: app/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
