apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: test-sops-secrets-operator
  namespace: default
spec:
  suspend: false
  secretTemplates:
    - name: some-secret
      stringData:
        username: someuser
        password: somepassword
    - name: some-other-secret
      stringData:
        token: sometoken
