apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sops-secrets-operator
    namespace: default
spec:
    suspend: false
    secretTemplates:
        - name: some-secret
          stringData:
            username: ENC[AES256_GCM,data:pqBMsbC5J9I=,iv:3R6aY/LD2dn1l0cHs8qOnThSGVfmoz3jXjSHybChgwc=,tag:d7JlRt8NJyRvi8q6Mg89DQ==,type:str]
            password: ENC[AES256_GCM,data:h7jnt0ormC1Zxs+u,iv:K0MtkkbVk1E0hUtw8E6aC0j9r6Mru195ZQpULn5+8bw=,tag:YR57q1OR5+Y0Fj2dzgFh+Q==,type:str]
        - name: some-other-secret
          stringData:
            token: ENC[AES256_GCM,data:T6q/nEpu+W1r,iv:kUugxoBzb7FDTq/oCAAJcflY/H8RVIr69yJxi7sNalA=,tag:iXSKDPq9isBYeE9zASBbaw==,type:str]
sops:
    age:
        - recipient: age1mrpulqqnyg6kkuhpfwgpkadgdw8ked7acjk4mkq4zd5fr8hwmsfqsnh69h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NDJXamtva0xvVUQ4VFhF
            QitPN2lkTGx0QkdkaVdEc0EzQjliL0V1aUVzCkVjbWRjUnBQNTh0LytaV2k0SWta
            Z2MrRlVLODZaWERYdVJFVG9wRE1SNGsKLS0tIGNxazcwTUp0dm1jbGIxVlhqejlt
            RitLbG4xeTZUQ3RiSk1QN3UzaHJZR1EKowjTSxnDdDDzwJ0VPe0zjOtuAAOvcGJ+
            lGxK9N1lpWZIXYb4XcUvBWomsOPiNxEtbww9n60/3vCCTCUOo5ot7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T08:43:53Z"
    mac: ENC[AES256_GCM,data:dJK4zEFKjR73Qo+adcPFRMyd2sbnfskUX5XdBnp1WljuIEh6CwyMEFMmvZN8th+w2tEYyJTekRWGYyZRU54J8BN7yVrSI+kpaEX7mO00gXC9g1IS2UMOHm2hKgH0OzhfdlXXH2Sb8DEAkHYitLmAmeGBwbQrDVtu+PhZoBkKz3E=,iv:tcZv1ctvQB/NGjXg7LdYYTc1x7xDdDWPO3I5UEMEyXM=,tag:HpO9iSUjFn9KJRiR4Y4ZlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
